# Generated by Django 5.2.7 on 2025-11-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='allow_display',
            field=models.BooleanField(default=False, help_text='Allow my personal pledge to be displayed publicly on the live screen.'),
        ),
    ]
