# Generated by Django 5.2.7 on 2025-11-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0002_submission_allow_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='personal_pledge_censored',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
