# Generated by Django 5.2.7 on 2025-11-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0003_submission_personal_pledge_censored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='allow_display',
            field=models.BooleanField(default=False),
        ),
    ]
