# Generated by Django 5.2.7 on 2025-11-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0004_alter_submission_allow_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='personal_pledge',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
