# Generated by Django 5.2.7 on 2025-11-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Site', max_length=255)),
                ('test_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
