# Generated by Django 5.2.7 on 2025-11-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy',
            field=models.TextField(blank=True, default=''),
        ),
    ]
