# Generated by Django 5.2.7 on 2025-11-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_privacy_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='privacy_policy',
            field=models.TextField(blank=True),
        ),
    ]
