# Generated by Django 5.2.7 on 2025-11-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sitesettings_privacy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='consent_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
