# Generated by Django 5.2.7 on 2025-11-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_consent_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='submission_form_heading',
            field=models.CharField(blank=True, default='Make your pledge', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='submission_form_subheading',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
