# Generated by Django 5.2.7 on 2025-11-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_submission_form_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='submission_form_subheading',
            field=models.TextField(blank=True, default=''),
        ),
    ]
