# Generated by Django 5.2.7 on 2025-11-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sitesettings_submission_form_subheading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='consent_text',
            field=models.TextField(blank=True, default='I agree for my information and pledge to be used for this event and for future analysis, research or reporting, in line with data protection law.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='We Are Just', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='submission_form_subheading',
            field=models.TextField(blank=True, default='Select the pledge that resonates with you, and if you’d like, add a personal one too — every promise helps shape a brighter future.'),
        ),
    ]
