# Generated by Django 5.2.7 on 2025-11-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='thank_you_page_heading',
            field=models.CharField(blank=True, default='Thank you for your pledge!', max_length=70),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='thank_you_page_subheading',
            field=models.TextField(blank=True, default='Your commitment is a vital step towards a more just and equitable world. Together, we can make a difference.'),
        ),
    ]
