# Generated by Django 5.2.7 on 2025-11-10 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_thank_you_page_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='visualisation_font_factor',
            field=models.IntegerField(default=100, help_text='A percentage factor to scale the base font size used in visualisations. E.g., 100 means 16px, 125 means 20px, etc.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='thank_you_page_heading',
            field=models.CharField(blank=True, default='Thank you!', max_length=70),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='thank_you_page_subheading',
            field=models.TextField(blank=True, default='Your pledge helps shape a brighter tomorrow.'),
        ),
    ]
