# Generated by Django 5.2.7 on 2025-11-10 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_visualisation_font_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='visualisation_font_factor',
            field=models.IntegerField(default=100, help_text='A percentage factor to scale the base font size used in visualisations. E.g., 100% is normal size, 80% is smaller, 120% is larger.', validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
