# Generated by Django 5.2.7 on 2025-11-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_sitesettings_visualisation_font_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='visualisation_hero_heading',
            field=models.CharField(blank=True, default='Together, we’re making change happen', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='visualisation_hero_subheading',
            field=models.TextField(blank=True, default='Together, we’re turning promises into progress — one step, one pledge, one brighter tomorrow at a time.'),
        ),
    ]
